package com.gtc.tradinggateway.service.okex.dto;

import com.google.common.collect.ImmutableMap;
import lombok.experimental.UtilityClass;

import java.util.Map;

/**
 * Created by Valentyn Berezin on 24.06.18.
 */
@UtilityClass
public class ErrorCodes {

    private static final Map<Long, String> TRANSLATION = ImmutableMap.<Long, String>builder()
            .put(10000L, "Required field, can not be null")
            .put(10001L, "Request frequency too high to exceed the limit allowed")
            .put(10002L, "System error")
            .put(10004L, "Request failed")
            .put(10005L, "'SecretKey' does not exist")
            .put(10006L, "'Api_key' does not exist")
            .put(10007L, "Signature does not match")
            .put(10008L, "Illegal parameter")
            .put(10009L, "Order does not exist")
            .put(10010L, "Insufficient funds")
            .put(10011L, "Amount too low")
            .put(10012L, "Only btc_usd ltc_usd supported")
            .put(10013L, "Only support https request")
            .put(10014L, "Order price must be between 0 and 1,000,000")
            .put(10015L, "Order price differs from current market price too much")
            .put(10016L, "Insufficient coins balance")
            .put(10017L, "API authorization error")
            .put(10018L, "borrow amount less than lower limit [usd:100,btc:0.1,ltc:1]")
            .put(10019L, "loan agreement not checked")
            .put(10020L, "rate cannot exceed 1%")
            .put(10021L, "rate cannot less than 0.01%")
            .put(10023L, "fail to get latest ticker")
            .put(10024L, "balance not sufficient")
            .put(10025L, "quota is full, cannot borrow temporarily")
            .put(10026L, "Loan (including reserved loan) and margin cannot be withdrawn")
            .put(10027L, "Cannot withdraw within 24 hrs of authentication information modification")
            .put(10028L, "Withdrawal amount exceeds daily limit")
            .put(10029L, "Account has unpaid loan, please cancel/pay off the loan before withdraw")
            .put(10031L, "Deposits can only be withdrawn after 6 confirmations")
            .put(10032L, "Please enabled phone/google authenticator")
            .put(10033L, "Fee higher than maximum network transaction fee")
            .put(10034L, "Fee lower than minimum network transaction fee")
            .put(10035L, "Insufficient BTC/LTC")
            .put(10036L, "Withdrawal amount too low")
            .put(10037L, "Trade password not set")
            .put(10040L, "Withdrawal cancellation fails")
            .put(10041L, "Withdrawal address not exsit or approved")
            .put(10042L, "Admin password error")
            .put(10043L, "Account equity error, withdrawal failure")
            .put(10044L, "fail to cancel borrowing order")
            .put(10047L, "this function is disabled for sub-account")
            .put(10048L, "withdrawal information does not exist")
            .put(10049L, "User can not have more than 50 unfilled small orders (amount<0.15BTC)")
            .put(10050L, "can't cancel more than once")
            .put(10051L, "order completed transaction")
            .put(10052L, "not allowed to withdraw")
            .put(10064L, "after a USD deposit, that portion of assets will not be withdrawable for the next 48 hours")
            .put(10100L, "User account frozen")
            .put(10101L, "order type is wrong")
            .put(10102L, "incorrect ID")
            .put(10103L, "the private otc order's key incorrect")
            .put(10216L, "Non-available API")
            .put(1002L, "The transaction amount exceed the balance")
            .put(1003L, "The transaction amount is less than the minimum requirement")
            .put(1004L, "The transaction amount is less than 0")
            .put(1007L, "No trading market information")
            .put(1008L, "No latest market information")
            .put(1009L, "No order")
            .put(1010L, "Different user of the cancelled order and the original order")
            .put(1011L, "No documented user")
            .put(1013L, "No order type")
            .put(1014L, "No login")
            .put(1015L, "No market depth information")
            .put(1017L, "Date error")
            .put(1018L, "Order failed")
            .put(1019L, "Undo order failed")
            .put(1024L, "Currency does not exist")
            .put(1025L, "No chart type")
            .put(1026L, "No base currency quantity")
            .put(1027L, "Incorrect parameter may exceeded limits")
            .put(1028L, "Reserved decimal failed")
            .put(1029L, "Preparing")
            .put(1030L, "Account has margin and futures, transactions can not be processed")
            .put(1031L, "Insufficient Transferring Balance")
            .put(1032L, "Transferring Not Allowed")
            .put(1035L, "Password incorrect")
            .put(1036L, "Google Verification code Invalid")
            .put(1037L, "Google Verification code incorrect")
            .put(1038L, "Google Verification replicated")
            .put(1039L, "Message Verification Input exceed the limit")
            .put(1040L, "Message Verification invalid")
            .put(1041L, "Message Verification incorrect")
            .put(1042L, "Wrong Google Verification Input exceed the limit")
            .put(1043L, "Login password cannot be same as the trading password")
            .put(1044L, "Old password incorrect")
            .put(1045L, "2nd Verification Needed")
            .put(1046L, "Please input old password")
            .put(1048L, "Account Blocked")
            .put(1050L, "Orders have been withdrawn or withdrawn")
            .put(1051L, "Order completed")
            .put(1201L, "Account Deleted at 00: 00")
            .put(1202L, "Account Not Exist")
            .put(1203L, "Insufficient Balance")
            .put(1204L, "Invalid currency")
            .put(1205L, "Invalid Account")
            .put(1206L, "Cash Withdrawal Blocked")
            .put(1207L, "Transfer Not Support")
            .put(1208L, "No designated account")
            .put(1209L, "Invalid api")
            .put(1216L, "Market order temporarily suspended. Please send limit order")
            .put(1217L, "Order was sent at ±5% of the current market price. Please resend")
            .put(1218L, "Place order failed. Please try again later")
            .build();

    public String translate(long code) {
        return TRANSLATION.getOrDefault(code, "Unknown code");
    }
}
